In [1]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [2]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_

True

In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [4]:
for file in os.listdir('./data/'):
    print(file)

story1.txt
story2.txt


In [5]:
f = open(r"C:\Users\DELL\full_stack_genai\Full-Stack-GenAI-Bootcamp-1.0\Class-06-07-11-12-Apr-Word2vec-with-practical\data\story1.txt",encoding='unicode_escape')

In [6]:
f

<_io.TextIOWrapper name='C:\\Users\\DELL\\full_stack_genai\\Full-Stack-GenAI-Bootcamp-1.0\\Class-06-07-11-12-Apr-Word2vec-with-practical\\data\\story1.txt' mode='r' encoding='unicode_escape'>

In [7]:
corpus =f.read()

In [8]:
corpus

'Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills, rivers, and green fields. The town was peaceful, and life moved slowly there, but Arjunâ\x80\x99s mind was always full of questions. He was very curious about how things worked and always wanted to know the reason behind everything he saw. His parents often smiled at his curiosity and encouraged him to keep learning.\n\nEvery day after school, Arjun would sit with his books and explore different topics. Sometimes he read about nature, sometimes about mathematics, and sometimes about machines. He was especially fascinated by science and technology. He wanted to understand how machines think, how computers solve problems, and whether they could ever become as intelligent as humans.\n\nAt school, Arjun was known as the boy who asked many questions. He would ask his teachers how electricity moves through wires, how radios send sound over long distances, and how calculators can solve problems

In [9]:
sent_tokenize(corpus)

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills, rivers, and green fields.',
 'The town was peaceful, and life moved slowly there, but Arjunâ\x80\x99s mind was always full of questions.',
 'He was very curious about how things worked and always wanted to know the reason behind everything he saw.',
 'His parents often smiled at his curiosity and encouraged him to keep learning.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'Sometimes he read about nature, sometimes about mathematics, and sometimes about machines.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think, how computers solve problems, and whether they could ever become as intelligent as humans.',
 'At school, Arjun was known as the boy who asked many questions.',
 'He would ask his teachers how electricity moves through wires, how radios send sound over long distances, and how

In [10]:
raw_sent = sent_tokenize(corpus)

In [11]:
for i in raw_sent:
  print(simple_preprocess(i))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'rivers', 'and', 'green', 'fields']
['the', 'town', 'was', 'peaceful', 'and', 'life', 'moved', 'slowly', 'there', 'but', 'arjunâ', 'mind', 'was', 'always', 'full', 'of', 'questions']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'wanted', 'to', 'know', 'the', 'reason', 'behind', 'everything', 'he', 'saw']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'keep', 'learning']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['sometimes', 'he', 'read', 'about', 'nature', 'sometimes', 'about', 'mathematics', 'and', 'sometimes', 'about', 'machines']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'thin

In [12]:
folder_path = r"C:\Users\DELL\full_stack_genai\Full-Stack-GenAI-Bootcamp-1.0\Class-06-07-11-12-Apr-Word2vec-with-practical\data"
story = []
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [13]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'rivers',
  'and',
  'green',
  'fields'],
 ['the',
  'town',
  'was',
  'peaceful',
  'and',
  'life',
  'moved',
  'slowly',
  'there',
  'but',
  'arjunâ',
  'mind',
  'was',
  'always',
  'full',
  'of',
  'questions'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'wanted',
  'to',
  'know',
  'the',
  'reason',
  'behind',
  'everything',
  'he',
  'saw'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'keep',
  'learning'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['sometimes',
  'he',
  'read',
  'about',
  'nature',
  'sometimes',
  'about',
  'mathematics',

In [14]:
len(story)

104

In [15]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'rivers',
 'and',
 'green',
 'fields']

In [16]:
story[1]

['the',
 'town',
 'was',
 'peaceful',
 'and',
 'life',
 'moved',
 'slowly',
 'there',
 'but',
 'arjunâ',
 'mind',
 'was',
 'always',
 'full',
 'of',
 'questions']

In [ ]:
sunny->100
Divyansh->6
Rahul->3

In [ ]:
# Word2Vec(..., sg=0)  # CBOW #by default
# Word2Vec(..., sg=1)  # Skip-gram

In [ ]:
# custom_model =gensim.models.Word2Vec(
#     window=10,
#     min_count=5,
#     vector_size=150
    
# )

## these all the value are the hyperparameter

In [17]:
custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150
    
)

In [18]:
custom_model.build_vocab(story)

In [19]:
len(custom_model.wv.index_to_key)

522

In [20]:
custom_model.corpus_count

104

In [21]:
custom_model.corpus_count

104

In [22]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

(10367, 14130)

In [23]:
custom_model.wv["arjun"]

array([-5.1301271e-03, -1.7417829e-03,  6.7157885e-03, -5.5188322e-03,
       -3.0091270e-03,  4.9821683e-03, -6.0459236e-03,  9.0341391e-03,
        3.4136185e-04,  7.6591456e-03,  7.1722935e-03, -3.2915436e-03,
       -5.4992130e-03,  7.5777383e-03, -2.4408007e-03,  1.6388344e-03,
       -2.1802604e-03,  7.8421589e-03, -9.8347722e-04, -8.1645849e-04,
       -7.1714091e-04, -2.6562759e-03,  6.6069425e-03,  7.5699377e-04,
       -1.8186718e-03,  1.7782088e-03,  1.0413069e-03, -6.9282204e-03,
        1.5577180e-03, -7.3952274e-03, -5.8790315e-03,  1.3918582e-03,
       -7.7251531e-03,  1.1298433e-03, -1.5702896e-03, -3.7148854e-04,
        1.0277362e-02,  7.5060455e-03,  5.9541161e-03, -4.5874189e-03,
        8.5039664e-04, -2.0420104e-03, -8.1088012e-03,  1.3898617e-03,
        1.5318777e-03, -1.6510750e-03,  1.0075298e-03, -4.6098065e-03,
        3.8034418e-03, -2.0454847e-04, -7.6668365e-03,  6.3380045e-03,
        5.5438239e-04,  7.2707380e-03,  4.2886008e-03,  2.8451208e-03,
      

In [24]:
len(custom_model.wv["arjun"])

150

In [25]:
custom_model.wv["farmers"]

array([ 2.0170249e-03, -2.3103904e-03,  2.8491765e-03,  3.5595123e-03,
        6.4188410e-03, -1.5393912e-03, -9.3246519e-04,  9.3030436e-03,
       -5.7900595e-03,  1.9439805e-03, -3.1890061e-03,  2.0874797e-03,
       -8.1795203e-03,  3.3492746e-03,  3.1446042e-03, -3.2200015e-03,
       -2.8109946e-03, -4.4972152e-03,  2.1160170e-03, -1.2449201e-03,
        2.4792033e-03, -2.5172301e-03,  7.8968266e-03,  1.3856789e-03,
       -3.4690367e-03, -3.8077238e-03, -2.9937979e-03, -5.7507441e-03,
        4.2234785e-03, -3.8323016e-03, -4.7112699e-03,  1.9789424e-03,
       -4.7574337e-03, -6.0876817e-03, -5.6121107e-03, -3.4758801e-04,
        5.4267724e-03,  3.0319898e-03,  4.9449624e-03,  2.0489995e-03,
        3.4825092e-03,  8.6715631e-04, -5.8556157e-03,  4.0033283e-03,
        1.7339946e-03,  2.1972898e-03,  7.6646259e-04,  2.7048599e-03,
        4.4228015e-03, -2.9471153e-03, -2.8912509e-03,  3.3591551e-04,
       -2.5355056e-04, -5.2391458e-03,  3.2922640e-03,  3.0040152e-03,
      

In [26]:
custom_model.wv["ai"]

array([ 2.0106065e-03, -1.1543516e-03, -5.5291881e-03, -2.7240559e-03,
       -3.4414919e-03, -5.2284040e-03, -1.3279392e-03, -1.2977464e-03,
        6.5596146e-03, -4.2915490e-05, -1.7657415e-04, -2.0174792e-03,
        3.5031615e-03,  5.0651915e-03, -7.4862232e-03, -2.1450556e-04,
        7.4126008e-03,  1.8040406e-03,  5.7508512e-03,  3.6311853e-03,
        2.2859205e-03, -3.2127637e-03, -1.2336134e-03,  5.9608323e-04,
        5.4250523e-03, -2.4203171e-03, -8.7823777e-04, -2.7203716e-03,
       -3.0336501e-03, -1.6596224e-03,  5.1005236e-03, -1.8861856e-03,
        4.2010634e-03,  8.9345610e-04, -6.6916817e-03,  4.5912047e-03,
        3.3523811e-03, -1.8887160e-03, -5.7416642e-03, -6.7389817e-03,
       -2.4958781e-03, -4.0281941e-03, -6.6011008e-03,  4.0388610e-03,
        6.9679450e-03,  4.8687640e-03,  6.2897978e-03, -1.1978529e-03,
       -1.3232932e-03, -4.0698694e-03,  5.0345254e-03,  3.9983662e-03,
        5.5237114e-03,  1.8953478e-03,  3.0680213e-03,  2.9359586e-03,
      

In [27]:
custom_model.wv.most_similar("arjun")

[('and', 0.6239988207817078),
 ('he', 0.5767260789871216),
 ('of', 0.5334029793739319),
 ('farmers', 0.5163472890853882),
 ('that', 0.5094478726387024),
 ('could', 0.5000675320625305),
 ('knowledge', 0.49590426683425903),
 ('can', 0.48948749899864197),
 ('were', 0.48360222578048706),
 ('the', 0.48218345642089844)]

In [28]:
custom_model.wv.most_similar("ai")

[('of', 0.39265087246894836),
 ('can', 0.343495637178421),
 ('very', 0.33828985691070557),
 ('days', 0.3203057646751404),
 ('crops', 0.28484970331192017),
 ('many', 0.2838762700557709),
 ('and', 0.27734920382499695),
 ('also', 0.2725212574005127),
 ('new', 0.2660059928894043),
 ('in', 0.26285532116889954)]

In [29]:
custom_model.wv.most_similar("engineer")

[('mind', 0.3324287533760071),
 ('were', 0.3198873698711395),
 ('him', 0.3156108856201172),
 ('and', 0.2977117896080017),
 ('many', 0.27336248755455017),
 ('system', 0.26936131715774536),
 ('who', 0.26669320464134216),
 ('slowly', 0.24670261144638062),
 ('wanted', 0.24368886649608612),
 ('follow', 0.24332013726234436)]

In [30]:
custom_model.wv.most_similar("data")

[('and', 0.4130496680736542),
 ('he', 0.3963492810726166),
 ('how', 0.3945333659648895),
 ('that', 0.39381590485572815),
 ('of', 0.3818056583404541),
 ('were', 0.38180094957351685),
 ('to', 0.3809477686882019),
 ('knowledge', 0.38059017062187195),
 ('arjun', 0.36848747730255127),
 ('building', 0.35558152198791504)]

In [31]:
custom_model.wv.doesnt_match(["arjun", "engineer", "programming", "farmers"])

'programming'

In [32]:
custom_model.wv.doesnt_match(["data", "model", "system", "river"])

'river'

In [33]:
custom_model.wv.doesnt_match(["weather", "crops", "farmers", "technology"])

'crops'

In [ ]:
google-news-million of Artical
neural and llm -> data hungry

In [34]:
custom_model.wv.similarity("ai", "technology")

0.1189804

In [35]:
custom_model.wv.similarity("arjun", "engineer")

0.1575414

## Assignment for this week

## add more data
## train for more epoch
## and check the accuracy of model
## check the embedding dimesion also

## inshort play with all the parameter

In [ ]:
SOTA/ Transformer

In [37]:
print(custom_model.wv.doesnt_match(["farmer", "crop", "soil", "ai"]))
print(custom_model.wv.doesnt_match(["data", "model", "algorithm", "river"]))
print(custom_model.wv.doesnt_match(["village", "river", "hill", "programming"]))
print(custom_model.wv.doesnt_match(["teacher", "student", "school", "weather"]))

ai
river
river
teacher
